[handle_call]
exten => start,1,Answer()
same => n,Set(FILE_LOCATION=${ARG1})
same => n,Set(CALLED_NUMBER=${ARG2})
same => n,Set(BRAODCAST_ID_CALLED=${ARG3})
same => n,Set(CALL_ID_CALLED=${ARG4})

same => n,Set(ODBC_UPDATE_CALL_TABLE_STATUS()=Answered,${CALL_ID_CALLED}) 


;same => n,AGI(play_and_detect.php,${FILE_LOCATION})

same => n,Background(${FILE_LOCATION})
;same => n,AMD()
;same => n,GotoIf($["${AMDSTATUS}" = "MACHINE"]?again:ndelay)
;same => n,NoOp(${AMDSTATUS} picked up)
;same => n(delay),WaitForSilence(2500)

;same => n(ndelay),NoOp(no delay)
    same => n,AGI(polly_aws_cli.sh,"To replay the message press 1, to remove your number from the system press 5. The message will now replay.")
 	same => n,Background(${TTS_MSG})
    same => n,WaitForSilence(2500)
    same => n(again),Background(${FILE_LOCATION})
    same => n,WaitExten(0)

exten => failed,1,NoOp(!!Call file failed!!)
    same => n,Set(CALL_ID_CALLED=${ARG4})
    same => n,ExecIf($["${REASON}" = "0"]?Set(FAIL_REASON=(not busy or congested)))
    same => n,ExecIf($["${REASON}" = "1"]?Set(FAIL_REASON=Hung up))
    same => n,ExecIf($["${REASON}" = "3"]?Set(FAIL_REASON=Ring timeout))
    same => n,ExecIf($["${REASON}" = "5"]?Set(FAIL_REASON=Busy))
    same => n,ExecIf($["${REASON}" = "8"]?Set(FAIL_REASON=Congestion))
    same => n,ExecIf($["${FAIL_REASON}" = ""]?Set(FAIL_REASON=Unknown))
    same => n,Set(ODBC_UPDATE_CALL_TABLE_STATUS()=Failed - ${FAIL_REASON},${CALL_ID_CALLED})

exten => 1,1,Goto(start,1)
	
exten => 5,1,Gosub(CONFIRM_REMOVE_NUMBER,start,1())

exten => i,1,AGI(polly_aws_cli.sh,"invalid selection")
	same => n,Background(${TTS_MSG})
	same => n,Goto(start,1)

exten => t,1,AGI(polly_aws_cli.sh,"Good Bye!!")
	same => n,Background(${TTS_MSG})
	same => n,Hangup()

